// Copia versionada de .github/skills/limpeza-encoding/scripts/glossario.json.
// Ao resolver uma pendencia nova, atualize os DOIS arquivos: o script Python e
// este, senao o front e o pipeline offline passam a limpar de formas diferentes.
//
// "#" representa o caractere perdido (U+FFFD). A conversao para o caractere
// real acontece em `carregarGlossario()`, no fim do arquivo.
//
// Convencoes (identicas as do script):
//   ordinais    "01o" -> "01", "No 29" -> "N 29", "3a ED" -> "3 ED"
//   acento solto "L´Acqua" -> "L'Acqua"
//   cedilha      sempre "c": "Servico", "Producao"

const MAPEAMENTOS: Record<string, string> = {
  "Produ##o": "Producao",
  "Refei##o": "Refeicao",
  "Tripula##o": "Tripulacao",
  "Manuten##o": "Manutencao",
  "Confec##o": "Confeccao",
  "Prepara##o": "Preparacao",
  "Organiza##o": "Organizacao",
  "Grava##o": "Gravacao",
  "Libera##o": "Liberacao",
  "Aprova##o": "Aprovacao",
  "Solu##o": "Solucao",
  "Lo##o": "Locao",
  "Nutri##o": "Nutricao",
  "Concentra##o": "Concentracao",
  "Dire##o": "Direcao",
  "Exporta##o": "Exportacao",
  "Reprodu##o": "Reproducao",
  "Licita##o": "Licitacao",
  "Lubrifica##o": "Lubrificacao",
  "posi##es": "posicoes",
  "a##car": "acucar",
  "A##car": "Acucar",
  "Descri##o": "Descricao",
  "M#quina": "Maquina",
  "m#q": "maq",
  "Impress#o": "Impressao",
  "Suspens#o": "Suspensao",
  "Emuls#o": "Emulsao",
  "Cart#o": "Cartao",
  "Padr#o": "Padrao",
  "Reuni#o": "Reuniao",
  "Lim#o": "Limao",
  "Ber#o": "Berco",
  "ber#o": "berco",
  "Servi#o": "Servico",
  "Crian#a": "Crianca",
  "Ma#a": "Maca",
  "Clich#": "Cliche",
  "Conclu#da": "Concluida",
  "In#cio": "Inicio",
  "T#tulo": "Titulo",
  "Jo#o": "Joao",
  "Andr#": "Andre",
  "Farmac#utica": "Farmaceutica",
  "Ind#stria": "Industria",
  "Qu#mica": "Quimica",
  "Medqu#mica": "Medquimica",
  "Farmoqu#micos": "Farmoquimicos",
  "Laborat#rio": "Laboratorio",
  "Pl#sticos": "Plasticos",
  "Sa#de": "Saude",
  "Braster#pica": "Brasterapica",
  "Itajub#": "Itajuba",
  "An#polis": "Anapolis",
  "Agua#": "Aguai",
  "c#psulas": "capsulas",
  "C#psulas": "Capsulas",
  "c#ps": "caps",
  "C#ps": "Caps",
  "c#p": "cap",
  "C#p": "Cap",
  "#leo": "Oleo",
  "#mega": "Omega",
  "#cido": "Acido",
  "#ndia": "India",
  "#nica": "Unica",
  "P#": "Po",
  "p#": "po",
  "P#o": "Pao",
  "P#ssego": "Pessego",
  "P#tals": "Petals",
  "N#": "N",
  "01#": "01",
  "C#lcio": "Calcio",
  "C#lcica": "Calcica",
  "C#l": "Cal",
  "S#dio": "Sodio",
  "S#dico": "Sodico",
  "Magn#sio": "Magnesio",
  "Pot#ssico": "Potassico",
  "Col#geno": "Colageno",
  "Hem#cias": "Hemacias",
  "Hialur#nico": "Hialuronico",
  "Zoledr#nico": "Zoledronico",
  "Tranex#mico": "Tranexamico",
  "Tiocolchicos#deo": "Tiocolchicosideo",
  "Ondansetr#n": "Ondansetron",
  "Etop#sido": "Etoposido",
  "Ep#sido": "Eposido",
  "T#tano": "Tetano",
  "Antirr#bico": "Antirrabico",
  "Antidift#rico": "Antidifterico",
  "Antielap#dico": "Antielapidico",
  "Anticrot#lico": "Anticrotalico",
  "Antiaracn#dico": "Antiaracnidico",
  "Antibotr#pico": "Antibotropico",
  "Antibotul#nico": "Antibotulinico",
  "Antilaqu#lico": "Antilaquetico",
  "Polivitam#nico": "Polivitaminico",
  "Probi#tico": "Probiotico",
  "Pedi#trico": "Pediatrico",
  "Gen#rico": "Generico",
  "L#quido": "Liquido",
  "T#pica": "Topica",
  "Qu#ntuplo": "Quintuplo",
  "Divis#ria": "Divisoria",
  "V#lvula": "Valvula",
  "Piv#": "Pivo",
  "An#is": "Aneis",
  "an#is": "aneis",
  "sach#s": "saches",
  "Sach#s": "Saches",
  "Hamb#rguer": "Hamburguer",
  "Sandu#che": "Sanduiche",
  "Avel#": "Avela",
  "Guaran#": "Guarana",
  "Maracuj#": "Maracuja",
  "Pur#": "Pure",
  "Ver#o": "Verao",
  "Beb#": "Bebe",
  "H#lito": "Halito",
  "Combust#vel": "Combustivel",
  "d'#gua": "d'agua",
  "#c.": "Ac.",
  "ACH#": "ACHE",
  "Z#": "Ze",

  // Marcas confirmadas em fonte externa: nome proprio destruido por U+FFFD nao
  // e dedutivel por regra, cada entrada abaixo custou uma checagem manual.
  "Cald#": "Calde",
  "Qualit#": "Qualita",
  "Iros#": "Irose",
  "Aid#": "Aide",
  "Mi#": "Mio",
  "Phit#ss": "Phitoss",
  "Gripalc#": "Gripalce",
  "Belgl#s": "Belglos",
  "Sarn#rico": "Sarnerico",
};

export const GLOSSARIO: Record<string, string> = Object.fromEntries(
  Object.entries(MAPEAMENTOS).map(([k, v]) => [k.replace(/#/g, "\uFFFD"), v]),
);
